### ISSUE TITLE
Processes % NaN for all displays on OS X High Sierra

### ISSUE THREAD

**Issue by PlutoniumProphet** [GitSquared/edex-ui#1061] opened 2021-03-06 11:03 UTC
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.7-pre`)
 - [X] `latest` (latest release, currently `v2.2.6`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [X] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [X] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem

Download from GitHub. Install .dmg over previous installation. Process metrics no longer display values and all displays are NaN. This is a regression as previous installation was correct. No other changes made to system or XQuartz before/after installation. Issue replicated across PID, NAME, CPU and MEM. 

![Screen Shot 2021-03-06 at 10 55 29](https://user-images.githubusercontent.com/39414420/110204543-7e453f80-7e6b-11eb-904c-8b87feda1f3b.png)

**Comment by GitSquared** [comment] 2021-03-06 11:10
Duplicate of #1052, fixed and awaiting release

**Closed by GitSquared** 2021-03-06 11:10 UTC
Labels: investigation

**Comment by PlutoniumProphet** [comment] 2021-03-06 11:17
Thanks. I clearly didn't search well enough!

**Comment by GitSquared** [comment] 2021-03-06 11:22
No problem! Hoping to release the fix soon but we're having some difficulties with automated builds.

**Comment by Itai-Nelken** [comment] 2021-03-06 11:52
> No problem! Hoping to release the fix soon but we're having some difficulties with automated builds.

@GitSquared I can try to build armv7l and arm64 appimages for the next release so all those fixes are not delayed.

**Comment by GitSquared** [comment] 2021-03-08 08:07
@Itai-Nelken thanks for the offer, i'm looking at getting a Pi anyway so hopefully we can see a patch release this week.
