### ISSUE TITLE
Hardware Description Issue

### ISSUE THREAD

**Issue by mikhanator** [GitSquared/edex-ui#885] opened 2020-11-12 10:59 UTC
Hey Gitsquared,

It could be a bug or it's an install thing (running 2.2.2 win10), but I can't find a config file or anything to change my **Manufacturer/Model/Chassis** as it only says **System manufacturer/System Product/Desktop**. While it's not the end of the world, it'd be nice to manually edit this.

![image](https://user-images.githubusercontent.com/74355177/98931513-3dc75c00-2532-11eb-996a-b0c54c152bd2.png)

Running as admin doesn't help it either. 
Everything else seems to work however.

Regards,

Mik

**Comment by GitSquared** [comment] 2020-11-12 12:18
Duplicate of #757

**Closed by GitSquared** 2020-11-12 12:18 UTC
