### ISSUE TITLE
Failed GeoIP databases downloads prints errors in the UI

### ISSUE THREAD

**Issue by Coder-ZJQ** [GitSquared/edex-ui#941] opened 2020-12-04 01:18 UTC
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.4`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem
I have reinstalled v2.2.4. First launch was fine. But after I `ctrl + shift + s` set the theme, save to disk and reload UI. These errors occurred.
![image](https://user-images.githubusercontent.com/15013685/101108861-6e218800-3610-11eb-9e5e-25d6a7899273.png)
![image](https://user-images.githubusercontent.com/15013685/101109151-28b18a80-3611-11eb-9751-4d0de11fcf09.png)
![image](https://user-images.githubusercontent.com/15013685/101110362-cad27200-3613-11eb-9e15-d40d1ce69cde.png)

**Comment by wrac4242** [comment] 2020-12-04 08:20
that was a recent issue, that I thought was fixed with the new release, possibly see if the downloaded version is v2.2.3 not v2.2.4

**Comment by Coder-ZJQ** [comment] 2020-12-04 08:29
The first screenshot shows the version v2.2.4
![image](https://user-images.githubusercontent.com/15013685/101140344-cdea5400-364d-11eb-91cd-eb7c8f92ca11.png)

**Comment by wrac4242** [comment] 2020-12-04 08:31
@GitSquared I think the issue is still here, i think others are still reporting it, such as the latest comment on #937

**Comment by GitSquared** [comment] 2020-12-04 08:42
It's technically a different one, I think I see what's going on here. @Coder-ZJQ could you confirm what's in `/Users/Joker/Library/Application Support/eDEX-UI/geoIPcache`? (not `-tmp`)

**Comment by GitSquared** [comment] 2020-12-04 08:46
(What's going on: a dependency is downloading geoIP databases in the background so it can display pins on the globe module. When you reload the UI that download is interrupted so it starts complaining about corrupted files - but it's capable of overwriting them anyway so we should just silence these errors.)

**Comment by kbarni** [comment] 2020-12-04 08:51
Yep...leaving eDEX-UI running for a few minutes after the first startup (when the network monitor goes back to 0) solves the issue.

**Comment by Coder-ZJQ** [comment] 2020-12-04 08:52
@GitSquared The directory is empty.
![image](https://user-images.githubusercontent.com/15013685/101142752-fe7fbd00-3650-11eb-9d60-3bf8abfa5356.png)

**Comment by GitSquared** [comment] 2020-12-04 08:58
Thanks for the info, I'll look into a fix.

**Comment by vastminecraft** [comment] 2020-12-07 20:33
yeah its been happening to with me on windows version    it only happens on wifi for me.  ethernet its fine but wifi has the problems

**Comment by GitSquared** [comment] 2020-12-08 08:32
Sorry for the wait, I'm hoping to get a fix rolling today. Issue is tracked upstream: https://github.com/GitSquared/node-geolite2-redist/issues/13

**Closed** 2020-12-08 16:37 UTC
Labels: bug, confirmed

**Comment by GitSquared** [comment] 2020-12-12 11:05
We should prbbly consider releasing this... v2.2.5?

**Comment by GitSquared** [comment] 2020-12-20 09:58
> We should prbbly consider releasing this... v2.2.5?

https://github.com/GitSquared/edex-ui/releases/tag/v2.2.5
