### ISSUE TITLE
no fullscreen

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#939] opened 2020-12-03 17:46 UTC
## Technical information
**Using version:**
 - `latest` (latest release, currently `v2.2.3`)

**Running on:**
 - Windows

**How comfortable you are with your system and/or IT in general:**
 - My machine is fully under my control, tell me what you need

---

## Problem

When starting edex, it does not overlap the taskbar, meaning its not fullscreen.

This seems to happen after changing the settings from `powershell.exe` to `cmd.exe` and fully restarting.
Changing it back does not fix it. I am not sure wether this happens with all settings.

**Comment by GitSquared** [comment] 2020-12-03 17:48
Duplicate of #920

**Closed by GitSquared** 2020-12-03 17:48 UTC
Labels: bug, investigation
