### ISSUE TITLE
Web version of eDEX-ui 

### ISSUE THREAD

**Issue by stevennt** [GitSquared/edex-ui#754] opened 2020-08-04 07:15 UTC
**Perceived idea awesomeness**
- [X] Wow, you don't have this yet???
- [X] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [X] Would need some work, but nothing impossible.
- [X] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

Detach eDEX-UI from "living on the host system". Allow it to live on the web. Kind of Wetty but a super cool version of it (eDEX-UI on the web): https://github.com/butlerx/wetty
Thanks.

**Comment by niklas2810** [comment] 2020-08-04 08:51
Additional requirements:

- Expose app via HTTP server
   - HTTPS via user configuration or built-in?
   - Run without User Interface on local machine
- Implement auth system and/or Integrate OS login system (OS support -> Linux only?)
- Rewrite all file system and terminal interaction to work via remote connection (currently depends on xterm)

I guess it would be a lot of work to implement such a mode, especially because most of the app's parts depend on libraries such as xterm and I'm not quite sure how well those support remote connections.

**Comment by stevennt** [comment] 2020-08-05 01:23
>>Rewrite all file system and terminal interaction to work via remote connection (currently depends on xterm)
Xterm.js may be very handy then. Project Wetty already addressed most of the issues you mentioned the only thing is that it isn't pretty/sci-fi.

**Comment by clragon** [comment] 2020-08-20 17:52
this is a duplicate of #488

**Closed** 2020-08-20 18:56 UTC
Labels: idea
