### ISSUE TITLE
EDEX-UI 2.2.2 WONT START UP. 

### ISSUE THREAD

**Issue by capacity99** [GitSquared/edex-ui#523] opened 2019-06-04 19:19 UTC
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)

**Running on:**
 - [x] Windows 7 
---

So basically, I foudn out EDEX, and I loved it. I used it on a university pc that has windows 10. And it worked perfect, but then, I went to my home, and started up my own pc to get it started!. And it installs. But dosent start up. I'm quite sad, I know how to use cmd so good. 

I don't know what to do. Haven't found my problem. :(
It dosent work with any old version.

**Comment by GitSquared** [comment] 2019-06-04 19:37
@capacity99 Could you give me some basics specs about your system? CPU, number of cores/threads, video card if any...

Could be a case of #505

**Comment by capacity99** [comment] 2019-06-05 13:28
Tarjeta de video AMD Raedon 460.
Windows 7 Service pack 2.
8RAM.
i3

**Comment by GitSquared** [comment] 2019-06-09 07:25
@capacity99 Could you tell me the exact model of the i3 processor?

**Comment by capacity99** [comment] 2019-06-11 01:00
Intel Core i3-6100

**Comment by GitSquared** [comment] 2019-06-15 13:54
That makes it a duplicate of #505. Closing.

**Closed by GitSquared** 2019-06-15 13:54 UTC
Labels: bug, duplicate
