### ISSUE TITLE
CPU usage is too high

### ISSUE THREAD

**Issue by JackMing0** [GitSquared/edex-ui#543] opened 2019-07-07 03:27 UTC
*The following (lightweight) template is made to better understand your view and what you think about your request. You are free to ignore it, but are encouraged to complete it.
We've seen lots of feature requests on this project, some were perhaps [too ambitious](https://github.com/GitSquared/edex-ui/issues/456) and some were [literally implemented overnight](https://github.com/GitSquared/edex-ui/issues/260). Don't be afraid to propose your ideas either way, we'll look at every one of them ;)
You can delete this introduction message if you want to.*

**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [x] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [x] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

*(Write your idea or feature request here)*
Edex - UI is a very nice piece of software! Can CPU usage is too high! It can't be used better

**Comment by GitSquared** [comment] 2019-07-07 09:41
What CPU do you have?
A lot of optimization work has been implemented in eDEX already. I'm afraid I can't do much more.

**Comment by giovannigiordano** [comment] 2019-07-09 12:35
@GitSquared I have the same issue with a MacBook Pro with an Intel i5-5257U

**Comment by Allsimon** [comment] 2019-07-09 13:07
<img width="237" alt="Capture d’écran 2019-07-09 à 15 04 13" src="https://user-images.githubusercontent.com/8037169/60890143-01f3f680-a25b-11e9-86a9-33fc7964541e.png">

Same here

**Comment by GitSquared** [comment] 2019-07-13 17:02
Thanks for sharing that screenshot @Allsimon. Unfortunately, the only abnormal thing I can see is your CPU temperature.

Please note that the "71.2%" displayed in the Top Processes panel is **per-core CPU usage** - which means the maximum value in your specific case would be 400% (4-cores, 8-threads CPU), so the **actual CPU-wide usage is 17.8%**.
I'm working on a UI update to make this easier to read & understand.

20% CPU usage is well within the expected range, considering that:
 - eDEX-UI, even though it was optimized since, wasn't built with performance in mind
 - Your MacBook's processor is [5 years old](https://ark.intel.com/content/www/us/en/ark/products/83505/intel-core-i7-4770hq-processor-6m-cache-up-to-3-40-ghz.html) and severely overheating (max rated temperature for this gen is 100°C).

I believe @giovannigiordano and @JackMing0 have similar setups.

I'm going to close this thread and prioritize the work I already started on fixing displayed CPU usage values - I'm hoping that was actually the issue here.

If you have any other questions or remarks, please send them - I still monitor closed threads.

**Closed by GitSquared** 2019-07-13 17:02 UTC
Labels: idea

**Comment by Allsimon** [comment] 2019-07-13 18:30
[My CPU](https://www.cpubenchmark.net/cpu.php?cpu=Intel+Core+i7-4770HQ+%40+2.20GHz) is really close in speed to the latest [Macbook pro](https://www.cpubenchmark.net/cpu.php?cpu=Intel+Core+i7-7700HQ+%40+2.80GHz).

For this screenshot, I left edex-ui idle with nothing else in the background.

I really don't think you should ignore this @GitSquared, it is totally unusable on Mac currently. Even clicking on the displayed keyboard has a 400-500 millisecond latency

**Comment by GitSquared** [comment] 2019-07-13 18:55
@Allsimon I focused on CPU usage and didn't think input latency was this bad, sorry.

While your CPU speed is indeed far from bad, maybe its integrated GPU is causing the problem. Could you give me the exact model/specs of your laptop so that I can verify all this?

Also, would you be able to open the dev console from inside edex and check if any error or seemingly unusual stuff pops up?

**Comment by Allsimon** [comment] 2019-07-15 14:55
I experience issue #222 (can't fix it on my side, sorry).

There is a memory leak too (it might be caused by #222, I'm not sure)...
In order to reproduce, you just have to open edex-ui, launch the console, take a heap snapshot every ~30seconds, the memory will grow till it crashes.

I'm on V2.2.2 - Electron 4.2.0 (macOS 10.14.5)

**Comment by danrobi11** [comment] 2020-10-24 11:13
Hello. Why is this closed? edex-ui uses so much cpu usage that it makes nosense to use it as it is right now

**Comment by GitSquared** [comment] 2020-10-24 11:15
Perhaps because it's >1 year old. Also, see #769.
