### ISSUE TITLE
Cannot use proprety "send" of undefiend MacOS 10.15.6 

### ISSUE THREAD

**Issue by kortbyoussama** [GitSquared/edex-ui#966] opened 2020-12-18 23:26 UTC
## Technical information
**Using version:**
 - [ ] `latest` (latest release, currently `v2.2.4`)
 

**Running on:**
 - [ ] macOS 10.15.6

**How comfortable you are with your system and/or IT in general:**
 - [ ] My machine is fully under my control, tell me what you need

---

## Problem
crash on startup, not working at all :/ 
![Screen Shot 2020-12-19 at 12 22 59 AM](https://user-images.githubusercontent.com/34894866/102672170-645f5f00-4190-11eb-99c1-55424ffcfc90.png)

**Comment by wrac4242** [comment] 2020-12-19 08:58
can you try seeing if running it on the master branch causes any issues, the readme has more detains

**Comment by GitSquared** [comment] 2020-12-20 09:12
Duplicate of #941

**Closed by GitSquared** 2020-12-20 09:12 UTC
Labels: investigation

**Comment by GitSquared** [comment] 2020-12-20 09:57
Just released v2.2.5 which should fix this!
