### ISSUE TITLE
Terminal panel now has white overlay, intentional change?

### ISSUE THREAD

**Issue by i0ntempest** [GitSquared/edex-ui#901] opened 2020-11-17 10:14 UTC
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Was like this a few days ago:
![Screen Shot 2020-11-17 at 05 09 12](https://user-images.githubusercontent.com/16017904/99376807-6da89380-2893-11eb-964e-b8e4876cf3f3.png)
With the latest commit (048feb5):
![Screenshot 2020-11-17 05 08 28](https://user-images.githubusercontent.com/16017904/99377011-ad6f7b00-2893-11eb-92a9-76f955d1ca60.png)

**Comment by GitSquared** [comment] 2020-11-17 10:19
I can't reproduce this and I checked the diff of the last few commits and can't see anything that would cause this so far. Could you share your theme file?

**Comment by i0ntempest** [comment] 2020-11-17 10:30
Actually I ran the build again and it's fine now. I guess its caused by me interrupting & continuing the build during the first run. Also notice that the title for the main terminal panel is missing in the first pic, any idea how to turn that on?

**Comment by GitSquared** [comment] 2020-11-19 14:29
> Also notice that the title for the main terminal panel is missing in the first pic, any idea how to turn that on?

It's retrieved at the OS level with the following command:

https://github.com/GitSquared/edex-ui/blob/048feb502b2b3b1ccd3ad8e3484d1b22cfe8766a/src/classes/terminal.class.js#L346

Replace `${PID}` with the pid of the shell launched by eDEX (find it in htop or any reasonable process monitoring utility). You can debug it from there, it's out of scope for this repo.

**Closed by GitSquared** 2020-11-19 14:29 UTC
Labels: bug, investigation

**Comment by 4xle** [comment] 2020-11-20 22:54
FWIW I also encountered this when compiling from source, had the same thing happen with the build crashing and then finishing successfully a second time. Nuking the dist folder and rebuilding worked, so probably some artifact from the unsuccessful build.
