### ISSUE TITLE
Can't Compile From Source on Raspberry Pi

### ISSUE THREAD

**Issue by Gopherslol** [GitSquared/edex-ui#538] opened 2019-06-26 19:59 UTC
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ x ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ x ] Linux (Raspbian Buster)
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ x ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

*(Write your report here)*
When trying to compile from source, after executing $ npm run install-linux I get the following:

npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> edex-ui@2.2.2 install-linux /home/pi/Documents/edex-ui-2.2.2
> npm install && cd src && npm install && ./../node_modules/.bin/electron-rebuild -f -w node-pty && cd ..

npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> electron@4.2.0 postinstall /home/pi/Documents/edex-ui-2.2.2/node_modules/electron
> node install.js

Downloading tmp-3526-0-electron-v4.2.0-linux-armv6l.zip
Error: GET https://github.com/electron/electron/releases/download/v4.2.0/electron-v4.2.0-linux-armv6l.zip returned 404
/home/pi/Documents/edex-ui-2.2.2/node_modules/electron/install.js:49
  throw err
  ^

Error: Failed to find Electron v4.2.0 for linux-armv6l at https://github.com/electron/electron/releases/download/v4.2.0/electron-v4.2.0-linux-armv6l.zip
    at Request.<anonymous> (/home/pi/Documents/edex-ui-2.2.2/node_modules/nugget/index.js:169:61)
    at Request.emit (events.js:189:13)
    at Request.onRequestResponse (/home/pi/Documents/edex-ui-2.2.2/node_modules/request/request.js:1062:10)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@4.2.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@4.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-06-26T19_03_41_473Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edex-ui@2.2.2 install-linux: `npm install && cd src && npm install && ./../node_modules/.bin/electron-rebuild -f -w node-pty && cd ..`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the edex-ui@2.2.2 install-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-06-26T19_03_42_263Z-debug.log

---
The debug.log file mentioned is:

0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v10.15.2
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'install-linux' ]
7 info using npm@5.8.0
8 info using node@v10.15.2
9 verbose run-script [ 'preinstall-linux', 'install-linux', 'postinstall-linux' ]
10 info lifecycle edex-ui@2.2.2~preinstall-linux: edex-ui@2.2.2
11 info lifecycle edex-ui@2.2.2~install-linux: edex-ui@2.2.2
12 verbose lifecycle edex-ui@2.2.2~install-linux: unsafe-perm in lifecycle true
13 verbose lifecycle edex-ui@2.2.2~install-linux: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/Documents/edex-ui-2.2.2/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
14 verbose lifecycle edex-ui@2.2.2~install-linux: CWD: /home/pi/Documents/edex-ui-2.2.2
15 silly lifecycle edex-ui@2.2.2~install-linux: Args: [ '-c',
15 silly lifecycle   'npm install && cd src && npm install && ./../node_modules/.bin/electron-rebuild -f -w node-pty && cd ..' ]
16 silly lifecycle edex-ui@2.2.2~install-linux: Returned: code: 1  signal: null
17 info lifecycle edex-ui@2.2.2~install-linux: Failed to exec install-linux script
18 verbose stack Error: edex-ui@2.2.2 install-linux: `npm install && cd src && npm install && ./../node_modules/.bin/electron-rebuild -f -w node-pty && cd ..`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16)
18 verbose stack     at EventEmitter.emit (events.js:189:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:189:13)
18 verbose stack     at maybeClose (internal/child_process.js:970:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
19 verbose pkgid edex-ui@2.2.2
20 verbose cwd /home/pi/Documents/edex-ui-2.2.2
21 verbose Linux 4.19.50+
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "install-linux"
23 verbose node v10.15.2
24 verbose npm  v5.8.0
25 error code ELIFECYCLE
26 error errno 1
27 error edex-ui@2.2.2 install-linux: `npm install && cd src && npm install && ./../node_modules/.bin/electron-rebuild -f -w node-pty && cd ..`
27 error Exit status 1
28 error Failed at the edex-ui@2.2.2 install-linux script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

**Comment by GitSquared** [comment] 2019-07-03 17:02
Could you run `uname -a` and give me the output? From your logs it seems like your Pi is using an old processor architecture (`armv6l`) that is not supported by Electron (and, by extension, eDEX) anymore.
Just want to confirm this.

**Comment by Chromecube** [comment] 2019-08-19 15:00
@GitSquared You are right, for Electron version 4.2.0 only ARMv7 (and higher) processor architecture versions are supported. All available downloads are listed here: https://github.com/electron/electron/releases?after=v5.0.1

@Gopherslol I guess your Pi is a bit old as only the first generation of Raspberry Pi's used ARMv6, the newer models use ARMv8. You can look it up here: https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications

**Comment by GitSquared** [comment] 2019-08-21 13:30
Closing this since the cause of the issue seems to have been found and OP hasn't answered in 2 months.

**Closed by GitSquared** 2019-08-21 13:30 UTC
Labels: bug, investigation
