### ISSUE TITLE
CPU intensive

### ISSUE THREAD

**Issue by presidentelect** [GitSquared/edex-ui#333] opened 2018-11-30 12:43 UTC
When running edex-ui my cpu usage jumps by ~50 percentage points, or more ( first try was from ~30 to ~80%, killed it and waited for the system to stabilize and tried again and it jumped from ~10% to ~80%)

I'm running Windows 10 64bit, Xeon 4 core (8 logical processors) 32 GB memory.

**Comment by GitSquared** [comment] 2018-11-30 12:50
Duplicate of #238

**Closed by GitSquared** 2018-11-30 12:50 UTC
