### ISSUE TITLE
EDEX-UI not opening after double-clicking on icon nothing responds at all

### ISSUE THREAD

**Issue by Et0hacker** [GitSquared/edex-ui#505] opened 2019-05-12 08:06 UTC
*The following (lightweight) template is made to avoid recurring questions in new bug reports and to facilitate problem diagnosis. You are free to ignore it, but filling it correctly will help a lot. Either way, thanks for taking the time to write a report.
You can delete this introduction message if you want to.*

## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.1`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

*(Write your report here)*

**Comment by RajTechKing** [comment] 2019-05-12 08:11
Yeah. SAME problem with me.

**Comment by GitSquared** [comment] 2019-05-12 08:13
Have you changed any settings? Could be related to #496

**Comment by Et0hacker** [comment] 2019-05-12 08:17
> Have you changed any settings? Could be related to #496

no i did nothing....just installed ur package as normal installation

**Comment by RajTechKing** [comment] 2019-05-12 08:22
In task manager, I can see two background process of EDEX_UI but none in the apps. It sort of loads, probably loads the two processes and then nothing happens.

**Comment by Et0hacker** [comment] 2019-05-12 08:24
> In task manager, I can see two background process of EDEX_UI but none in the apps. It sort of loads, probably loads the two processes and then nothing happens.

same here bro... I can see two background process of EDEX_UI but none in the apps. probably loads the two processes and then nothing happens. OS: Win 7 64-bit

**Comment by RajTechKing** [comment] 2019-05-12 08:26
This is what I get when starting from CMD:-

 Γû║  start     Starting eDEX-UI v2.2.1
i  info      With Node 10.11.0 and Electron 4.1.4
i  info      Renderer is Chrome 69.0.3497.128
Γû║  Startup   Initialized timer...
i  info      Base config dir is C:\Users\acer\AppData\Roaming\eDEX-UI
[ ]  pending   Loading settings file...
ΓêÜ  success   Settings loaded!
[ ]  pending   Creating new terminal process on port 3000
(node:7260) UnhandledPromiseRejectionWarning: Error: File not found:
    at new WindowsPtyAgent (C:\Users\acer\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:53:36)
    at new WindowsTerminal (C:\Users\acer\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\Users\acer\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\index.js:29:12)
    at new Terminal (C:\Users\acer\AppData\Local\Programs\edex-ui\resources\app.asar\classes\terminal.class.js:1:8188)
    at App.app.on (C:\Users\acer\AppData\Local\Programs\edex-ui\resources\app.asar\_boot.js:180:11)
(node:7260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by GitSquared** [comment] 2019-05-12 08:26
Do you fellas know how to launch it from a cmd/powershell window? It could print out some interesting logs.

**Comment by GitSquared** [comment] 2019-05-12 08:28
@RajTechKing Are you also on Win7?

**Comment by RajTechKing** [comment] 2019-05-12 08:29
No I am on windows 8.1

**Comment by GitSquared** [comment] 2019-05-12 08:32
Okay. From the logs it seems that some internal Windows dependency can't be found on your system - and I'm guessing the same thing is happening for @Et0hacker

Those pre-compiled packages have only been tested on win10, I'll see if I can maybe relink some stuff by building on older versions.

In the meantime if you're feeling adventurous you could try to build from source (instructions are in the readme) and see if the same error appears.

**Comment by RajTechKing** [comment] 2019-05-12 08:33
I also tried compatibility settings for Windows 7 and Windows Vista. Still doesn't work.

**Comment by Et0hacker** [comment] 2019-05-12 08:33
![photo_2019-05-12_14-02-53](https://user-images.githubusercontent.com/50541295/57579788-bb825580-74be-11e9-856c-b17fd9448088.jpg)
![photo_2019-05-12_14-03-07](https://user-images.githubusercontent.com/50541295/57579789-bc1aec00-74be-11e9-948b-e04cb50e3fd5.jpg)

**Comment by RajTechKing** [comment] 2019-05-12 08:34
> 
> 
> Okay. From the logs it seems that some internal Windows dependency can't be found on your system - and I'm guessing the same thing is happening for @Et0hacker
> 
> Those pre-compiled packages have only been tested on win10, I'll see if I can maybe relink some stuff by building on older versions.
> 
> In the meantime if you're feeling adventurous you could try to build from source (instructions are in the readme) and see if the same error appears.

Alright. I am not so good at programming(I only know basics of programming) but I guess I'll try. Thanks for your time.

**Comment by Et0hacker** [comment] 2019-05-12 08:36
> > Okay. From the logs it seems that some internal Windows dependency can't be found on your system - and I'm guessing the same thing is happening for @Et0hacker
> > Those pre-compiled packages have only been tested on win10, I'll see if I can maybe relink some stuff by building on older versions.
> > In the meantime if you're feeling adventurous you could try to build from source (instructions are in the readme) and see if the same error appears.
> 
> Alright. I am not so good at programming(I only know basics of programming) but I guess I'll try. Thanks for your time.

@GitSquared same applies for me
@RajTechKing lets try toghether

**Comment by Et0hacker** [comment] 2019-05-12 08:38
@GitSquared do u have any development group? In platforms like Telegram Etc.

**Comment by RajTechKing** [comment] 2019-05-12 08:38
Yeah. We might help out.(HOPEFULLY :D)

**Comment by GitSquared** [comment] 2019-05-12 08:40
@Et0hacker No, sorry. I'm pretty much working alone on this one.

**Comment by GitSquared** [comment] 2019-05-12 08:40
To build the thing on Windows you'll need to have Node.js installed and then it should be just a matter of putting in the right commands in order.

**Comment by Et0hacker** [comment] 2019-05-12 08:41
> To build the thing on Windows you'll need to have Node.js installed and then it should be just a matter of putting in the right commands in order.

ok i'll try but....u also pls work on this

**Comment by RajTechKing** [comment] 2019-05-12 08:47
Hey @Et0hacker do you have telegram? If yes, email me your mobile no on rajvajpayee059@gmail.com and I'll Connect with you.

**Comment by GitSquared** [comment] 2019-05-12 08:50
@Et0hacker Yes of course. I'm just suggesting, you don't have to do anything.

**Comment by Et0hacker** [comment] 2019-05-12 08:50
> Hey @Et0hacker do you have telegram? If yes, email me your mobile no on [rajvajpayee059@gmail.com](mailto:rajvajpayee059@gmail.com) and I'll Connect with you.

tell me ur telegram id, adding you now by id

**Comment by RajTechKing** [comment] 2019-05-12 08:52
I can't find anything like ID.

**Comment by Et0hacker** [comment] 2019-05-12 08:52
> I can't find anything like ID.

open your telegram and on search type: @iamjinay

**Comment by RajTechKing** [comment] 2019-05-12 08:53
If you are looking for username, it is @RajTechKing

**Comment by shivamshukl4** [comment] 2019-05-17 02:56
@GitSquared
I'm using windows 10 pro 64bit.
The system installed the EDEX_UI without any issues.
When launching it through shortcut it shows nothing.
But two EDEX_UI processes running in background.
Please help me.☺

**Comment by dkozinn** [comment] 2019-05-19 17:50
I just installed  2.2.2 on Windows 10 64-bit 1903 and the same problem is happening. I didn't see anything in the release notes about this, so I assume this is yet ot be fixed?

**Comment by GitSquared** [comment] 2019-05-19 18:29
@dkozinn Indeed, the latest version is just an emergency vuln fix. I haven't taken the time to research this issue yet - it's quite difficult since everything works flawlessly on my machine, so I need to figure out a way to reproduce the bug first.

I'm currently studying for final exams so I won't give an estimated ETA just yet. I'll make sure to look into it before the next release, though.

**Comment by dkozinn** [comment] 2019-05-19 18:50
@GitSquared Thanks for letting me know. When you're done with finals if there's anything I can do to let, please let me know. More than happy to run debug versions, etc.

Good luck with your finals.

**Comment by GitSquared** [comment] 2019-07-13 18:27
f1dbf08

Okay, after taking some time to look into this again, It seems that the shell program eDEX attempts to load as a terminal back-end is not found, which due to ~~my laziness~~ a lack in error handling in the early stages of the startup procedure, causes eDEX to silently crash.

The default shell program for fresh windows installs of edex is `powershell.exe`.
Maybe some $PATH misconfigurations prevent it from being found; in which case this issue would be solved by the yet-to-be-released automatic shell path resolution feature (f1dbf08).

Otherwise, powershell might be simply missing from your systems - a quick way to verify that is to open the quick launch window (Win+R) and type `powershell.exe` then enter.
If a blue command line appears, you're good, and hopefully the next update of edex will be able to correctly find your shell.

**Comment by GitSquared** [comment] 2019-07-13 18:30
In the meantime, I believe you should be able to work around this issue by starting eDEX once (to generate configuration files) and replacing the value in the `shell` entry of the [setting file](https://github.com/GitSquared/edex-ui/wiki/settings.json) to `cmd.exe`.

**Comment by dkozinn** [comment] 2019-07-13 18:42
I do have powershell on my machine though shell was set to bash which perhaps is why it was failing? In any case, I set shell to powershell.exe and it seems to be working now.

**Comment by GitSquared** [comment] 2019-07-13 18:57
The shell was set to bash??
This is really weird. Thanks for the info, I'll check what's going on.

Just to confirm, this is on the v2.2.2 release?

**Comment by dkozinn** [comment] 2019-07-13 19:13
I believe that I was running 2.2.1. I've replaced that with 2.2.2 now but I can see that the settings file hasn't been touched since I manually modified it.  Obviously it's still working fine after that change.

**Comment by GitSquared** [comment] 2019-07-13 19:34
It is programmed to never overwrite the config file. Which is why I hope the 7225 people who downloaded v2.2.1 on Windows didn't get a broken default configuration. :grimacing:

Seems weird because if it was a code error I'd expect to have much more feedback about this. I hope to figure out what happened soon.

**Comment by dkozinn** [comment] 2019-07-13 19:52
I think I started with an earlier version, then upgraded to 2.2.1, so perhaps it goes back further?

**Comment by GitSquared** [comment] 2019-07-13 22:03
I checked and the specific line of code that sets `powershell` as the default option on Windows is correct and hasn't moved in 2 years. I'm not sure how you got `bash` to appear in your config.

I'm going to wait for @Et0hacker's feedback on this.
In the meantime, you gave me an idea for a small logging feature I'm going to implement.

**Comment by dkozinn** [comment] 2019-07-14 03:08
I wonder if when I ran it the first time, I set that myself to bash figuring I'd get that instead of powershell? In other words ... user error. I don't remember doing that, but I can't swear that I didn't either.

**Comment by GitSquared** [comment] 2019-07-14 09:46
Thought about this too. I need OP's feedback to confirm what's in his configuration file.

**Comment by GitSquared** [comment] 2019-09-02 13:02
This thread is starting to rot and is not really relevant due to the changes in the shell path finder that I committed in the past few months. I'm going to close it.

***If you're having this issue, do the following:***

- Check the `shell` value in your configuration file (see this repo's wiki for up-to-date information about where to find it), verify that there is a valid path to powershell/cmd/git-bash in there,
- If the path is non-existent and you haven't edited your configuration, comment here with the value you found,
- If you have edited the config, revert it back to a valid path, or remove the settings file to let eDEX automatically find default values at startup.

**Closed by GitSquared** 2019-09-02 13:02 UTC
Labels: bug, investigation, windows
