### ISSUE TITLE
Virtual keyboard highlights during password typing

### ISSUE THREAD

**Issue by UserXGnu** [GitSquared/edex-ui#394] opened 2019-01-16 16:43 UTC
Although I like the idea of having a virtual keyboard to be used on touchscreen devices, when using on notebook or PC, it is still rendered and for me, the lack of option to remove it is an issue. But another problem is that when typing passwords the keys being pressed through the physical keyboard are highlighted which is, of course, not good.

thx for the amazing job, btw

**Comment by GitSquared** [comment] 2019-01-16 18:02
There has been a lot of discussion about both topics on Hacket News and Reddit - not that I blame you for missing it.

The `tron-notype` example theme has been added to show that with the current customization possibilites, you can actually remove the visual keyboard - if you want to add this to any other theme, just copy the "injectCSS" line from that one.

I do have to agree that simply visually hiding the keyboard is not the best option, and I'm working on a way to make the current "modules" implementation in eDEX more flexible, which means in the future you should be able to choose which modules to load up and at what places - that includes the visual keyboard.

The new graphical settings editor & "modal" windows implementation shipped in v2 is a first step towards this goal of providing more options for the user, eventually reaching to #334.

As for hiding typing feedback on password, currently it is technically not possible for eDEX to detect when you enter password fields. I could add a hacky "fix" by spying on the terminal output and triggering some fonction when "password" is detected, or something like that, but I'm not really keen on those kinds of messy workarounds.

Thanks for opening an issue, I'm going to close this one but if you have anymore comments or questions feel free to ask on this thread - i still watch closed issues most of the time.

**Closed by GitSquared** 2019-01-16 18:02 UTC

**Comment by 4goettma** [comment] 2019-04-11 11:35
What's about adding an option to disable the visual highlighting on the screen keyboard while pressing physical keys?

**Comment by GitSquared** [comment] 2019-04-11 16:35
@4goettma I'm not really keen on that, might as well wait for the upcoming modular update and just remove the on-screen keyboard.

It might work as a keyboard shortcut rather than an option, though...
Like, press shortcut to disable visual feedback, type your password, press shortcut to enable it back again.
Could even add a nifty little warning message below the shell that would get triggered when the word "password" is detected in the output.
Shortcut could be something like `Ctrl+Shift+P`?
What do you think?

**Comment by 4goettma** [comment] 2019-04-11 18:40
Sounds good - exactly what we need. But there might be people who never want to see the visual feedback, so an option in the settings file would be still useful.

**Comment by GitSquared** [comment] 2019-04-11 19:13
I'm not so sure that there would be that much people wanting to keep a half-functioning touchscreen keyboard. Imo either you've got a physical one and you might as well just remove it from your screen, or you're on a touch display and need the visual feedback.

**Comment by 4goettma** [comment] 2019-04-12 18:47
What's about tablets like the Microsoft Surface which has an additional keyboard or using a bluetooth keyboard for a tablet?

**Comment by GitSquared** [comment] 2019-04-17 08:43
Well, they have a physical keyboard plugged in then.

**Comment by 4goettma** [comment] 2019-04-18 08:49
Thought about switching between using the keyboard and removing it. But I don't mind, I don't own one. As stated before, a hotkey for disabling it would be nice to have.

**Comment by GitSquared** [comment] 2019-04-18 12:05
I'll implement this before the next release.

**Comment by GitSquared** [comment] 2019-04-18 15:56
![Peek 2019-04-18 17-52](https://user-images.githubusercontent.com/24496417/56374153-cc62e280-6202-11e9-9ad2-6721fa09b38a.gif)

Here it is. Hitting Ctrl+Shift+P (either through physical or virtual keyboards, as with all shortcuts) will toggle a special "password mode" where the on-screen keyboard is greyed out and doesn't give any visual input feedback.
It still works though, so hitting modifiers like Shift or Fn will change the displayed keyboard layout.

**Comment by veeshi** [comment] 2019-08-30 15:43
Possible bug, when the keyboard is re-enabled using ctrl-shft-p the shift key is highlighted, even if another key is pressed, until shift is pressed again which unhighlights it

**Comment by GitSquared** [comment] 2019-08-30 15:57
@veeshi on which version does this happen?

**Comment by veeshi** [comment] 2019-09-03 07:12
Latest version, v2.2.2

**Comment by GitSquared** [comment] 2019-09-03 07:53
I can't reproduce this behavior. What keyboard layout are you using? @veeshi

**Comment by veeshi** [comment] 2019-09-03 09:25
English UK, international Qwerty

**Comment by GitSquared** [comment] 2019-09-04 09:46
![ezgif com-gif-maker](https://user-images.githubusercontent.com/24496417/64244147-0f92c900-cef8-11e9-8edc-0c4eed504a66.gif)

Tested on both `master` (v3.0.0-pre) and v2.2.2. Anything unusual about your setup...?
