### ISSUE TITLE
Can't Change Terminal Emulator 

### ISSUE THREAD

**Issue by SkeleBones** [GitSquared/edex-ui#791] opened 2020-10-25 20:54 UTC
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [x] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

If I change the shell and restart the terminal, it refuses to launch. If I change it back it doesn't start either. The only way I can start it again after changing it is to delete the settings.json file.

**Comment by AkechiShiro** [comment] 2020-10-26 23:05
I haven't encountered this issue when changing the shell from `bash` to `zsh` for instance. What is the shell emulator you're trying to set in the settings.json ?
Also I take it you have bash installed ?

**Comment by Jr7000750** [comment] 2020-10-27 11:19
Hi

Thnkx For the info, i still cant log in
I use wireless internet And a Kodi with rasperig

Verstuurd vanaf mijn iPhone

**Comment by SkeleBones** [comment] 2020-10-27 12:59
I have bash installed. I am trying to use PowerShell 7-preview. It is installed in the normal place.

**Comment by AkechiShiro** [comment] 2020-10-27 13:22
I'd like to know from what kind of environnement are you trying to launch the terminal is ? Is an X11 server launched ? Or are you trying to launch the terminal in a TTY ?

If you're trying from a TTY then that explains the problem.

**Comment by SkeleBones** [comment] 2020-10-27 13:49
I'm using X11.

**Comment by SkeleBones** [comment] 2020-10-27 14:38
Another thing is it does sort of launch. It just doesn't open fully. I can see it running in the task manager but it never starts the UI.

**Comment by GitSquared** [comment] 2020-10-27 14:40
What version?

**Comment by SkeleBones** [comment] 2020-10-27 15:43
v2.2.2

**Comment by parkerlreed** [comment] 2020-10-27 15:54
https://github.com/GitSquared/edex-ui/issues/769

>Should I submit a new issue?
It depends. As mentioned above, any comeback to this project would start with a code rewrite, effectively eliminating all current bugs (and surely creating new ones, but that's another story).
If you're on v2.2.2, the latest released version, chances are your problem is fixed in the never-released v3.0. To access it, you'll have to build from source.
If you're on v3, please submit an issue, but beware that I might not get back to you in a timely manner.

**Comment by SkeleBones** [comment] 2020-10-27 16:53
Same issue on v3.

**Comment by SkeleBones** [comment] 2020-10-27 19:16
Also, I seemed to have formated this Bug Report wrong.

**Comment by GitSquared** [comment] 2020-10-27 20:14
> Also, I seemed to have formated this Bug Report wrong.

It's fine, however as you probably guessed if you looked over at #769 i might not get back to you anytime soon, sorry. Off the top of my head i can't figure out what's happening here.

**Comment by SkeleBones** [comment] 2020-10-27 20:42
Yeah, it is fine. I can just use the stock shell for now.

**Comment by AkechiShiro** [comment] 2020-10-27 20:50
Does the stock shell work ? I could try to install the Powershell preview 7 on my distro and give it a try to see if I can reproduce your issue.

**Comment by SkeleBones** [comment] 2020-10-27 22:08
Didn't mean to do that.

**Comment by SkeleBones** [comment] 2020-10-28 02:38
Semi Log

(node:13784) UnhandledPromiseRejectionWarning: Error: File not found: C:\Program
    at new WindowsPtyAgent (C:\edex-ui\src\node_modules\node-pty\lib\windowsPtyAgent.js:74:36)
    at new WindowsTerminal (C:\edex-ui\src\node_modules\node-pty\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\edex-ui\src\node_modules\node-pty\lib\index.js:28:12)
    at new Terminal (C:\edex-ui\src\classes\terminal.class.js:404:33)
    at App.<anonymous> (C:\edex-ui\src\_boot.js:234:11)
(node:13784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Jr7000750** [comment] 2020-10-28 08:36
Hi i try To download Bash today

Verstuurd vanaf mijn iPhone

**Comment by bleek42** [comment] 2020-11-02 05:56
Just wanted to chime in and say @SkeleBones is not alone. I just discovered eDEX-UI today and having problems changing the default shell. Using Windows 10 and trying to change settings.json from the default Powershell to Bash.

**Comment by GitSquared** [comment] 2020-11-02 07:54
Possibly related: #740 #698

**Comment by Jr7000750** [comment] 2020-11-02 09:46
Thnkx

**Comment by SkeleBones** [comment] 2020-11-02 10:44
I tried what it said in #698, it didn't work.

**Comment by rozbrajaczpoziomow** [comment] 2020-11-02 21:10
I think I know what's going on,
> (node:13784) UnhandledPromiseRejectionWarning: Error: File not found: C:\Program [...]

I think when you're trying to call powershell, you're trying to do smth like this:
start C:\Program Files\...
But its not quoted... And then windows thinks (I think it thinks that way) like "C:\Program" is the path and "Files\..." is the argument.

**Comment by bleek42** [comment] 2020-11-02 23:59
> 
> 
> I think I know what's going on,
> 
> > (node:13784) UnhandledPromiseRejectionWarning: Error: File not found: C:\Program [...]
> 
> I think when you're trying to call powershell, you're trying to do smth like this:
> start C:\Program Files...
> But its not quoted... And then windows thinks (I think it thinks that way) like "C:\Program" is the path and "Files..." is the argument.
> 
> ![Screenshot](https://user-images.githubusercontent.com/58668179/97919736-9a6b8f80-1d58-11eb-8c72-8221f524bb84.png)

soooo in settings.json, right.... in the default terminal, where it now just says powershell.exe, instead of changing it to simply bash.exe, I change it to the entire path where bash.exe is actually located..? still get the same problem. I save these new settings and restart eDEX, and the program just does not start.

**Comment by rozbrajaczpoziomow** [comment] 2020-11-03 07:40
> 
> 
> > I think I know what's going on,
> > > (node:13784) UnhandledPromiseRejectionWarning: Error: File not found: C:\Program [...]
> > 
> > 
> > I think when you're trying to call powershell, you're trying to do smth like this:
> > start C:\Program Files...
> > But its not quoted... And then windows thinks (I think it thinks that way) like "C:\Program" is the path and "Files..." is the argument.
> > ![Screenshot](https://user-images.githubusercontent.com/58668179/97919736-9a6b8f80-1d58-11eb-8c72-8221f524bb84.png)
> 
> soooo in settings.json, right.... in the default terminal, where it now just says powershell.exe, instead of changing it to simply bash.exe, I change it to the entire path where bash.exe is actually located..? still get the same problem. I save these new settings and restart eDEX, and the program just does not start.

I don't think it's an issue with your settings.json file, but propably how the TTY is started? Not really sure, because I don't know how it's handled, but maybe I'll try to look into the source code and figure it out.

**Comment by Animus-Surge** [comment] 2020-11-16 02:17
I’ll have a look. Seems like reading paths from the settings.json messed up if there’s any spaces in it.

**Comment by rozbrajaczpoziomow** [comment] 2020-11-16 22:37
And also, now I figured out why full paths to like C:\Program Files\... don't work... It's literally trying to start C:\Program.. _("C:\Program Files\test".split(" ")[0] == "C:\Program")_

**Comment by GitSquared** [comment] 2020-11-17 08:35
> It's literally trying to start C:\Program.. ("C:\Program Files\test".split(" ")[0] == "C:\Program")

Oh that totally makes sense! I've got an idea for a fix, hang on :)

**Comment by GitSquared** [comment] 2020-11-17 09:27
Could you try this out?

**Comment by Animus-Surge** [comment] 2020-11-17 13:06
> Could you try this out?

It worked on my end, at least it feels like it. I set the emulator to nodejs (stored in the program files folder) and it ran without any issues

**Closed** 2020-11-18 20:26 UTC
Labels: bug, investigation
