### ISSUE TITLE
Latest Release (Windows) is Running Terribly

### ISSUE THREAD

**Issue by cmdrflexo** [GitSquared/edex-ui#238] opened 2018-11-22 15:28 UTC
Tried this out today on two win10 machines. Had to force kill the process on both machines after it immediately redlined the CPU at a constant 100% with 60-75% of that being the exe. On one machine it chewed up over 3.8 GB of RAM before I closed it.
WMIC/wmiprvse runs wild.
I haven't dipped into the source to see what's going on, but i'd be surprised if this needed to be so excessive.

PC:
Win10
AMD FX-9590 (4.72 GHz)
32 GB
GTX 970

Tablet:
Win10
Intel Atom Z8700
4 GB

I can only venture a guess...maybe windows defender has the application in a choke hold or something. It seems odd, since I don't see any similar issues being brought up here.

I'd like to help figure this out. Reply with thoughts or suggestions I can try out.
Easy to repeat and provide more details if needed.

**Comment by GitSquared** [comment] 2018-11-22 15:50
Yeah I've heard some reports that CPU/mem usage was absolutely nuts on windows for some people. Could you post of screenshot of the task manager with eDEX running?

**Comment by cmdrflexo** [comment] 2018-11-22 22:08
@GitSquared 
![image](https://user-images.githubusercontent.com/4148613/48923066-3c01bb00-ee79-11e8-9e46-1630d61469d6.png)

**Comment by GitSquared** [comment] 2018-11-23 06:02
I think i got an idea for a "fix", but i don't believe i've found the root cause yet.

I'll need to rewrite a significant portion of the code, though, so don't expect it to land before at least this weekend.

**Comment by oshnix** [comment] 2018-11-23 09:11
One more thing, when i was switching themes a lot, memory and cpu usage increased significantly. My OS is the same - win10x64

**Comment by GitSquared** [comment] 2018-12-12 19:38
Would anyone be willing to try out this [test version](https://mega.nz/#!FoF3SSgK!tRXm0j16ef0QyW6qogweyQBqkQqn1Ls5J-WwziDuhtM) (from the [multithread-experiment](https://github.com/GitSquared/edex-ui/tree/multithread-experiment) branch)?

Performance should be quite heavily improved on this one, note that it doesn't support the Globe module yet 'cause i need to tweak this one a bit too.

I'll test it out myself on some machines but just wanted to give a heads up to anyone still interested.

**Comment by presidentelect** [comment] 2018-12-12 20:22
Much better than it was.  Now it uses about 15% cpu on my machine when not doing anything other than the default graphics/top/etc.

Machine: xeon E3-1505M 2.8GHz (4 core/8 thread), 32 GB memory

**Comment by erixom** [comment] 2018-12-12 20:37
Performance in general much better on here, I could not test it with different themes because they wouldn't load due to an error with the globe not working. I have to say this sadly does not work that well in touch mode on my 2 in 1 but works great on my normal laptop.

**Comment by a494413872** [comment] 2018-12-13 03:34
test version is  much better, but still cost 90% CPU。hope you can fix it，this is a great UI

**Comment by planetahuevo** [comment] 2018-12-15 13:53
Same problem here. 
Is it possible to remove the file drive checks on Windows using a setting? 
I think that also use a lot of resources (takes a while to check at start for example) and I do not use that at all on windows. Windows explorer is not the best tool on windows and have that opened all time is not useful.
Thanks!

**Comment by GitSquared** [comment] 2018-12-15 19:46
> I think that also use a lot of resources (takes a while to check "available space" at start for example)

**Comment by GitSquared** [comment] 2018-12-22 13:12
Update: I've finished the multithreaded work distribution script, re-enabled the globe and locked the 3D render's framerate to 30 FPS, which at least on my machine had a significant (40%) CPU impact.

Working on updating to Electron v4 which just came out yesterday, and then i'll do another round of testing.

**Comment by GitSquared** [comment] 2018-12-24 16:02
I did a bit of testing to see how the performance improvements coming in 2.0.0 are affecting this.

*Here's a comparative table of performance across multiple key eDEX versions:*

Version number | Average CPU usage | Average RAM usage | Average GPU usage | Additional remarks
-------------- | ----------------- | ----------------- | ----------------- | ------------------
1.0.0 | 35%\* | 400 Mo\* | 25-30% (spikes) | \*If anything prevents the ping and net statistics subprocesses to run smoothly, eDEX quickly starts leaking memory (reached **>5 Gb** on my test) and CPU usage jumps to **90%**
1.1.2 | 30% | 410 Mo | 25% | This version was already a bit less likely to spike when subprocesses failed, for some reason
2.0.0-pre | 15% | 510 Mo | 9% | CPU & GPU usage is much more stable (due to locking the framerate to 30FPS and upgrading Electron, among other things). A bit more RAM usage because of added features like sound effects. Could not reproduce the "leak" bug from v1.


Testing was done on a - quite powerful - Lenovo Yoga machine with the following notable specs:
 - Windows 10 Home x64
 - Intel Core i5-8250U Quad-Core, 8 Threads 1.6 GHz (up to 3.4 GHz boost)
 - Intel UHD Graphics 620 (Integrated graphics, clock: 1.150 MHz) with DirectX 12 support
 - 8 Go of 2400 MHz SODIMM memory

For each version tested, eDEX was ran for about 15 minutes with a busy (looping `tracert`) `cmd.exe` as the underlying shell. Nothing else running in the background, except default Win10 services. Laptop was plugged in.

2.0.0 will be released before mid-january I think. Note that the performance improvements are even more important on *nix systems, because they didn't have multithreading at all.

**Closed by GitSquared** 2018-12-24 16:02 UTC
Labels: bug, windows
