### ISSUE TITLE
Error on Start: TypeError

### ISSUE THREAD

**Issue by GFA-SkyRanger** [GitSquared/edex-ui#1031] opened 2021-02-11 23:47 UTC
TypeError: Cannot read property 'en' of undefined

Uncaught TypeError: Cannot read property 'en' of undefined at
...resources\app.asar\node_modules\xterm-addon-ligatures\lib\xterm-addon-ligatures.js 9:485

**Comment by wrac4242** [comment] 2021-02-12 07:08
hi, which operating system are you using, and which version are you attempting to run?

**Comment by hkdb** [comment] 2021-02-22 08:33
I am getting the same error. I am on Pop! OS 20.04 LTS...

**Comment by hkdb** [comment] 2021-02-22 08:40
Here is the output if run from the terminal:

```
▶  start     Starting eDEX-UI v2.2.5
ℹ  info      With Node 12.16.3 and Electron 10.2.0
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/hkdb/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /usr/bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
✔  success   Terminal back-end initialized!
☐  pending   Starting multithreaded calls controller...
✔  success   Multithreaded controller ready
ℹ  info      Creating window...
ℹ  info      Multithread worker started at 114146
☒  complete  Frontend window created!
…  watching  Waiting for frontend connection...
ℹ  info      Multithread worker started at 114145
ℹ  info      Multithread worker started at 114144
ℹ  info      Multithread worker started at 114147
ℹ  info      Multithread worker started at 114157
ℹ  info      Multithread worker started at 114158
ℹ  info      Multithread worker started at 114159
[114051:0222/003825.322125:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x184850d3cc00] GL_INVALID_OPERATION: Framebuffer is incomplete.
[114051:0222/003825.325568:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x184850d3cc00] GL_INVALID_OPERATION: Framebuffer is incomplete.
[114051:0222/003825.328923:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x184850d3cc00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[114051:0222/003825.329164:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x184850d3cc00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[114051:0222/003825.408236:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x184850d3cc00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[114051:0222/003825.409109:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x184850d3cc00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[114051:0222/003825.615722:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x184850d3cc00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
✔  success   Connected to frontend!
◼  Startup   Timer run for: 12.74s
ℹ  info      Resized TTY to  138 029
ℹ  info      UpdateChecker: Running latest version.
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UJ5k0nm/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UJ5k0nm/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UJ5k0nm/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UJ5k0nm/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UJ5k0nm/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UJ5k0nm/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UJ5k0nm/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UJ5k0nm/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UJ5k0nm/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
☒  complete  Terminal exited { exitCode: 0, signal: 0 } undefined
☒  complete  Shutting down...
```

I am wondering if it has to do with the default locale settings or lack there of?

**Comment by GitSquared** [comment] 2021-02-22 10:31
Might be, what's your locale/region?

**Comment by hkdb** [comment] 2021-02-23 03:22
Here are my locale settings:
```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

**Comment by GitSquared** [comment] 2021-02-24 15:02
> `LANGUAGE=en_US:en`

I've never seen this format before, could you try removing the `:en` part and see if it works? Seems to coincide with the error message you're getting, too.

**Comment by GFA-SkyRanger** [comment] 2021-02-24 18:47
> 
> 
> hi, which operating system are you using, and which version are you attempting to run?

I am on Win7 SP2
And i was using the latest version.

I had searched for this error, and this error seems to be a recent one and nobody had fixed it til now so i deleted this Program.

**Comment by wrac4242** [comment] 2021-02-24 18:51
seems to be a cross OS issue, which might help possibly. could someone who is having this issue try running a prebuilt version, and running from source

**Comment by hkdb** [comment] 2021-03-18 22:24
I was trying to compile without a lot of luck but ended up trying the 2.26 build instead and the problem is fixed in this build... at least for Pop! OS 20.04.

**Comment by wrac4242** [comment] 2021-03-20 07:33
you dont have to compile it from source, just run it from source
but what errors did you get when you tried to compile?

**Closed** 2021-10-19 20:50 UTC
