### ISSUE TITLE
Accented characters only work on onscreen keboard.

### ISSUE THREAD

**Issue by KjartanOli** [GitSquared/edex-ui#897] opened 2020-11-16 21:04 UTC
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Pretty much what it says in the title. I can use special characters such as á, í, é, ó on the onscreen keyboard, but typing the same characters on my physical keyboard just results in the non-accented version of the character.

**Comment by GitSquared** [comment] 2020-11-16 21:50
Duplicate of #469

**Closed by GitSquared** 2020-11-16 21:50 UTC
Labels: bug, investigation
