### ISSUE TITLE
Key repeat does not work

### ISSUE THREAD

**Issue by znfrench** [GitSquared/edex-ui#275] opened 2018-11-24 01:44 UTC
I'm running the latest release (installed today) on OSX 10.13.6.  When I hold down a (physical) keyboard key it does not repeat like it would in a normal terminal (or any other app).  Strange!  Makes using vim hard.

**Comment by GitSquared** [comment] 2018-11-24 07:10
Duplicate of #242 - Not much i can do about this one, sadly

**Closed by GitSquared** 2018-11-24 07:10 UTC
