### ISSUE TITLE
TypeError: Cannot read property 'getExtension' of null: Uncaught TypeError: Cannot read property 'getExtension' of null

### ISSUE THREAD

**Issue by bannsec** [GitSquared/edex-ui#228] opened 2018-11-21 19:39 UTC
✖  error     TypeError: Cannot read property 'getExtension' of null: Uncaught TypeError: Cannot read property 'getExtension' of null
⬤  debug     at /home/user/edex-ui/src/assets/vendor/encom-globe.js 29518:34

**Comment by GitSquared** [comment] 2018-11-21 19:59
Duplicate of #217

**Closed by GitSquared** 2018-11-21 19:59 UTC

**Comment by didavid0609** [comment] 2019-02-01 20:07
Thank you for the update for V 2.1, but this still does not work after the update, my graphics card is Intel HD Graphics 3000 384 MB on a 2011 MacBook Air core i5.
![screenshot 2019-02-01_21-03-23-410](https://user-images.githubusercontent.com/45569459/52146793-1bb65f80-2665-11e9-8614-557b3e619be8.jpg)
