### ISSUE TITLE
TypeError: Cannot read property of 'en'of undefined (Linux)

### ISSUE THREAD

**Issue by OfficialRuby** [GitSquared/edex-ui#927] opened 2020-12-01 02:30 UTC
Program started but panic after few seconds with the error message "_Cannot read property of 'en'of undefined_"

![Screenshot from 2020-12-01 03-22-48](https://user-images.githubusercontent.com/68361698/100690242-59ca5a80-3386-11eb-818e-0b1f2d4db8e0.png)

### Terminal output after crash

[20894:1201/032145.543170:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x30c3f9754300] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[20894:1201/032145.543491:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x30c3f9754300] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485
✖  error     TypeError: Cannot read property 'en' of undefined: Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UP2vKXb/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js 9:485

**Comment by Animus-Surge** [comment] 2020-12-01 23:53
Can you specify which distro you are using as well as the edex version?

**Comment by GitSquared** [comment] 2020-12-03 21:09
Duplicate of #924

**Closed by GitSquared** 2020-12-03 21:09 UTC
Labels: bug, investigation
